# Generated by Django 2.1.7 on 2019-03-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_last_name', models.CharField(max_length=45)),
                ('author_first_name', models.CharField(max_length=45)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['author_last_name', 'author_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='webVotingApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('judge_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_last_name', models.CharField(max_length=45)),
                ('member_first_name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['member_last_name', 'member_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_1', models.CharField(choices=[('PR', 'Poor'), ('CM', 'Common'), ('GD', 'Good'), ('OT', 'Outstanding'), ('SP', 'Superlative')], max_length=2)),
                ('criteria_2', models.CharField(choices=[('PR', 'Poor'), ('CM', 'Common'), ('GD', 'Good'), ('OT', 'Outstanding'), ('SP', 'Superlative')], max_length=2)),
                ('criteria_3', models.CharField(choices=[('PR', 'Poor'), ('CM', 'Common'), ('GD', 'Good'), ('OT', 'Outstanding'), ('SP', 'Superlative')], max_length=2)),
                ('criteria_4', models.CharField(choices=[('PR', 'Poor'), ('CM', 'Common'), ('GD', 'Good'), ('OT', 'Outstanding'), ('SP', 'Superlative')], max_length=2)),
                ('criteria_5', models.CharField(choices=[('PR', 'Poor'), ('CM', 'Common'), ('GD', 'Good'), ('OT', 'Outstanding'), ('SP', 'Superlative')], max_length=2)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='webVotingApp.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='webVotingApp.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='webVotingApp.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='webVotingApp.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge', to='webVotingApp.Member'),
        ),
        migrations.AddField(
            model_name='judge',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='webVotingApp.Year'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='webVotingApp.Year'),
        ),
    ]
