# Generated by Django 2.1.5 on 2019-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='criteria_1',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria_2',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria_3',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria_4',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='criteria_5',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2),
        ),
    ]
