# Generated by Django 2.1.5 on 2019-03-31 19:49
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

AUTHORS =[
    {'first_name': 'Helen', 'last_name': 'DeWitt'},
    {'first_name': 'Jonathan', 'last_name': 'Franzen'},
    {'first_name': 'Kazuo', 'last_name': 'Ishiguro'},
    {'first_name': 'Sheila', 'last_name': 'Heti'},
    {'first_name': 'Elena', 'last_name': 'Ferrante'},
    {'first_name': 'Maggie', 'last_name': 'Nelson'},
    {'first_name': 'Roberto', 'last_name': 'Bolano'},
    {'first_name': 'Paul', 'last_name': 'Beatty'},
    {'first_name': 'Rachel', 'last_name': 'Cusk'},
    {'first_name': 'Ian', 'last_name': 'McEwan'},
    {'first_name': 'Joan', 'last_name': 'Didion'},
    {'first_name': 'Ben', 'last_name': 'Lerner'},
    {'first_name': 'Rachel', 'last_name': 'Kushner'},
    {'first_name': 'Percival', 'last_name': 'Everett'},
    {'first_name': 'Jeffrey', 'last_name': 'Eugenides'},
    {'first_name': 'Michel', 'last_name': 'Houellebecq'},
    {'first_name': 'Gary', 'last_name': 'Indiana'},
    {'first_name': 'Edward', 'last_name': 'Jones'},
    {'first_name': 'Philip', 'last_name': 'Roth'},
    {'first_name': 'Alan', 'last_name': 'Hollinghurst'},
    {'first_name': 'Mary', 'last_name': 'Gaitskill'},
    {'first_name': 'Cormac', 'last_name': 'McCarthy'},
    {'first_name': 'Frederick', 'last_name': 'Seidel'},
    {'first_name': 'Junot', 'last_name': 'Diaz'},
    {'first_name': 'Hilary', 'last_name': 'Mantel'},
    {'first_name': 'Elif', 'last_name': 'Batuman'},
    {'first_name': 'Aimee', 'last_name': 'Bender'},
    {'first_name': 'Helen', 'last_name': 'Oyeyemi'},
    {'first_name': 'Emmanuel', 'last_name': 'Carrere'},
    {'first_name': 'Colson', 'last_name': 'Whitehead'},
    {'first_name': 'Gillian', 'last_name': 'Flynn'},
    {'first_name': 'Zadie', 'last_name': 'Smith'},
    {'first_name': 'Hilton', 'last_name': 'Als'},
    {'first_name': 'Karl Ove', 'last_name': 'Knausgaard'},
    {'first_name': 'Donna', 'last_name': 'Tartt'},
    {'first_name': 'Jenny', 'last_name': 'Offill'},
    {'first_name': 'Miriam', 'last_name': 'Toews'},
    {'first_name': 'Claudia', 'last_name': 'Rankine'},
    {'first_name': 'Fred', 'last_name': 'Moten'}
]


def add_author_data(apps, schema_editor):
    author_class = apps.get_model('webVotingApp', 'Author')
    for author in AUTHORS:
        try:
            duplicate_object = author_class.objects.get(
                author_first_name=author['first_name'],
                author_last_name=author['last_name']
            )
            print('Duplicate author entry not added to author table:',
                  author['first_name'], author['last_name']
                  )
        except ObjectDoesNotExist:
            author_object = author_class.objects.create(
                author_first_name = author['first_name'],
                author_last_name = author['last_name']
            )


def remove_author_data(apps, schema_editor):
    author_class = apps.get_model('webVotingApp', 'Author')
    for author in AUTHORS:
        author_object = author_class.objects.get(
            author_first_name=author['first_name'],
            author_last_name=author['last_name']
        )
        author_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0002_auto_20190331_1919'),
    ]

    operations = [ migrations.RunPython(
        add_author_data,
        remove_author_data
    )
    ]
